### ISSUE TITLE
would be nice to have last comits

### ISSUE THREAD

**Issue by hubyhuby** [isaced/crystal-web-framework-stars#7]
Amber s last commit is 6 motnh old to date for example

**Comment by paulocoghi** [comment]
The code of [`list2md.cr`](https://github.com/isaced/crystal-web-framework-stars/blob/master/list2md.cr) which is older than your comment is already adding the last commit to the README table.

If this is the desired output, then this issue can be closed :slightly_smiling_face: 

![image](https://github.com/user-attachments/assets/80285708-53b0-4145-923c-b84be5f5f2c3)

**Comment by hubyhuby** [comment]
Great thanks a lot.
Have a nice day.
